services:
  app_economia:
    image: mrxder/docker-apache-php7.2-mysql-phpmyadmin
    container_name: app_registros
    restart: always
    ports:
      - "8080:80"
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=economia_hogar
      - MYSQL_USER=devroot
      - MYSQL_PASSWORD=123
    volumes:
      # Archivos PHP
      - "/mnt/360C17970C17516B/git/app_registros:/var/www/html"
      # MySQL usa almacenamiento interno del contenedor (sin volumen NTFS)
